version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "5000:5000"  # Expose backend API port
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    volumes:
      - ./backend/.env:/app/.env
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
